### ISSUE TITLE
Facebook Adapter Not Ready

### ISSUE THREAD

**Issue by j3k0** [googleads/googleads-mobile-ios-mediation#167] opened 2019-10-28 10:30 UTC
After calling `GADMobileAds startWithCompletionHandler`, I get the following status:

**GADMediationAdapterFacebook** is **Not Ready;No such adapter in the application**.

Code:
```objectivec
    [[GADMobileAds sharedInstance] startWithCompletionHandler:^(GADInitializationStatus *status){
        NSLog(@"GADMobileAds: %@", status.adapterStatusesByClassName);
    }];
```

Log:
```
{
    GADMediationAdapterFacebook = "<GADAdapterStatus: 0x600003b124a0; state = Not Ready;No such adapter in the application.>";
    GADMobileAds = "<GADAdapterStatus: 0x600003be6e40; state = Ready>";
}
```

Of course, I followed the guide on how to setup the Facebook adapter.

When I run the mediation-test-suite. The ad units with mediation show the Facebook adapter as `Present: YES, Ready: NO`. Even though, loading and displaying facebook banners and interstitial works from the test suite.

Unfortunately, the Admob SDK **never** selects this adapter in my app (probably considering it to be not ready)...

Any idea?

EDITS: typos

**Comment by maninomula** [comment] 2019-11-15 21:13
Hello @j3k0 , Thanks for bringing up this issue. Is there any test app you can send us, as we are not able to reproduce this issue on our side?

**Comment by callMeMakerRen** [comment] 2019-12-30 02:25
i find this issue , because the adapter version is not match, but in practice ,it can still load from facebook ,but for safety, better to match the version

**Comment by maninomula** [comment] 2020-01-24 20:49
Closing this issue as it has been resolved.

**Closed by maninomula** 2020-01-24 20:49 UTC

**Comment by gypsicoder** [comment] 2020-05-28 15:22
@callMeMakerRen how to know that which version is a matching version? Is there any list?

**Comment by rudreshway** [comment] 2024-02-22 12:21
WebContent process (0x1170180c0) took 1.1217 seconds to launch
Adapter Name: com.google.ads.mediation.facebook.FacebookMediationAdapter, Description: <GADAdapterStatus: 0x28240cc80; state = Not Ready;No such adapter in the application.>, Latency: 0.0000
Adapter Name: GADMobileAds, Description: <GADAdapterStatus: 0x28240d380; state = Ready>, Latency: 0.0147
GADMobileAds: {
    GADMobileAds = "<GADAdapterStatus: 0x28240d380; state = Ready>";
    "com.google.ads.mediation.facebook.FacebookMediationAdapter" = "<GADAdapterStatus: 0x28240cc80; state = Not Ready;No such adapter in the application.>";
}.   in iOS  we are getting this error 
 versions are 

GoogleMobileAdsMediationFacebook (6.14.0.0)
Google-Mobile-Ads-SDK (10.11.0)
GoogleMobileAdsMediationInMobi (10.6.0.0)
FBAudienceNetwork (6.14.0)
FBSDKCoreKit (16.3.1)
 Xcode: 15.0.1 
OS: iOS
Native platform

**Comment by SzGajdzica** [comment] 2025-06-25 09:53
Same issue @rudreshway. I have issues with all adapters, i am adding them manually. I can use the code that the libraries provides, but Google Ads does not seem to see it and returns not ready No such adapter in the application.
