### ISSUE TITLE
CTA Button no responding

### ISSUE THREAD

**Issue by wanght** [googleads/googleads-mobile-ios-mediation#92] opened 2018-12-13 17:34 UTC
when use UnifiedNativeAd loads admob ads, everything is OK, but when FAN ads loaded, texts and mediaView are all correct, but the CTA button and adChoiceView are no responding ...

**Comment by maninomula** [comment] 2018-12-18 21:21
Hi @wanght ,

Thanks for bringing up the issue. We are taking a look in to it and will get back to you once we find something.

**Comment by maninomula** [comment] 2019-02-08 20:51
Hi @wanght ,

A new version of the GoogleMobileAds SDK has been released that has the fix for this issue. Please take a look and get back to us if you have any question.

Thanks
Mani

**Closed** 2019-02-12 21:54 UTC

**Comment by shubhendu1988** [comment] 2020-05-20 12:38
Any updates for this issue, as similar issue I am also facing, Using Google Ads Manager sdk ('Google-Mobile-Ads-SDK', '7.57.0') and show Facebook ads via mediation. On receiving FB Ads CTA does not work where as in receiving google ads CTA works. As per google documentation UserInteration for UIBUtton needs to be false. Making it true makes FB ads CTA function but stops Google ads CTA. 

The workaround was to use UILabel/UIImageView. But here the problem is to show animation on tapping UILabel. 

Please update
